In [2]:
import pandas as pd
import numpy as np

## Inline code with backticks

```
print('3 backticks or')
print('indent 4 spaces')
```

    # code block
    hold my beer!
    print('Hello word!')

$a=\frac{b}{c}$

***

|Name|Phone Number|
|:--:|:--:|
|Thinh|0964621015|


- thinh
# Ky tu hy lap
|Symbol|Script|
|:---:|:---:|
|$\pi$|\alpha|
|$A$|A|
|$\beta$|\beta|
|$B$|B|
|$\gamma$|\gamma|
|$\Gamma$|\Gamma|
$\Pi$
$\phi$
$\Phi$
$\varphi$
$\theta$


$\infty$

$\equiv$
$\times$

$k_n^2$ =
$k_n+1$

### Chinh hop
$C = \frac{n!}{k!(n-k!)}$

### Matrix 
$\binom{2}{6}$

### Square Root
$\sqrt[n]{5}$

    integral
$\int(x^2+2)$ + $\int\limits_a^b(2x+3)$

### Dao Ham
$\lim_{dx\to0}\frac{f(x +dx)-f(x)}{dx} = f'(x)$

### Pytago Equation
$c =\sqrt{a^2+b^2}$

# Big title
## Medium title
### and more
#### more
##### more .....

$Denta$

In [12]:
a = [[1,2,3,4,5,6],
     [7,8,9,10,11,12],
     [13,14,15,16,17,18],
     [19,20,21,22,23,24]]
a = np.array(a)
print(a)
print('type of arr_a:', a.dtype)
print(a.shape)
print('a.size:',a.size)
print('a.itemsize:', a.itemsize)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type of arr_a: int32
(4, 6)
a.size: 24
a.itemsize: 4


In [24]:
a[:, 0::5] =0 
a[0::3, :] = 0

In [25]:
print(a)

[[ 0  0  0  0  0  0]
 [ 0  8  9 10 11  0]
 [ 0 14 15 16 17  0]
 [ 0  0  0  0  0  0]]


In [26]:
b = np.array([[1,2,3,4,5,6],
     [7,8,9,10,11,12],
     [13,14,15,16,17,18],
     [19,20,21,22,23,24]])
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [29]:
print(b.reshape(2,3,2,2)) # 4-demensional

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]

  [[ 9 10]
   [11 12]]]


 [[[13 14]
   [15 16]]

  [[17 18]
   [19 20]]

  [[21 22]
   [23 24]]]]


In [36]:
c = b.copy()
c = c[ (c>5)&(c<10)] 
c

array([6, 7, 8, 9])

In [37]:
c = np.delete(c, [1,2])

In [38]:
c

array([6, 9])

In [39]:
d = b.copy()
print(d)
print(np.delete(d, d[1:2,2:4]))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[ 1  2  3  4  5  6  7  8  9 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [46]:

id(b)

2765620196496

In [3]:
c = np.random.randint(2,100, 10)
c

array([50, 23, 57, 45, 18, 73, 29,  8, 81, 88])

In [6]:
c[[True, False]*8]

array([50, 57, 18, 29, 81])